Repository limbonaut/limboai, pull requests merged in 2024-07, with the labels that each got.

#154 GHA improvements
  .github/workflows/linux.yml
  .github/workflows/web.yml
Labels: github-actions

#157 Improved layout for large displays (optional)
  demo/project.godot
  editor/limbo_ai_editor_plugin.cpp
  editor/limbo_ai_editor_plugin.h
Labels: enhancement

#158 Fix BlackboardPlan arrays shouldn't be shared between instanced agents
  blackboard/bb_variable.cpp
  blackboard/bb_variable.h
  blackboard/blackboard_plan.cpp
Labels: bug

#159 Improve documentation tooltips
  demo/demo/ai/tasks/arrive_pos.gd
  demo/demo/ai/tasks/back_away.gd
  demo/demo/ai/tasks/face_target.gd
  demo/demo/ai/tasks/get_first_in_group.gd
  demo/demo/ai/tasks/in_range.gd
  demo/demo/ai/tasks/is_aligned_with_target.gd
  demo/demo/ai/tasks/move_forward.gd
  demo/demo/ai/tasks/pursue.gd
  demo/demo/ai/tasks/select_flanking_pos.gd
  demo/demo/ai/tasks/select_random_nearby_pos.gd
  editor/task_palette.cpp
  editor/task_palette.h
Labels: enhancement

#161 Fix new task script path don't update after changing the setting
  editor/limbo_ai_editor_plugin.cpp
  editor/limbo_ai_editor_plugin.h
Labels: bug

#162 Fix error when opening scene with a `BTPlayer`
  bt/bt_player.cpp
Labels: bug

#172 Fix BTPlayer.restart() crash
  bt/bt_player.cpp
Labels: bug

#174 GHA: Add Linux & Windows ARM64 builds
  .github/actions/setup-linux-toolchain/action.yml
  .github/workflows/gdextension.yml
  .github/workflows/ios.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: github-actions

#176 LimboHSM: Fix process_input is not enabled in active substate
  hsm/limbo_hsm.cpp
Labels: bug

#177 Hide `update_mode` property for non-root HSMs
  demo/demo/assets/fonts/junction_bold.otf.import
  demo/demo/assets/fonts/knewave_regular.ttf.import
  demo/demo/scenes/showcase.tscn
  hsm/limbo_hsm.cpp
  hsm/limbo_hsm.h
  util/limbo_string_names.cpp
  util/limbo_string_names.h
Labels: enhancement
