Repository limbonaut/limboai, pull requests merged in 2024-08, with the labels that each got.

#180 Fix error if `changed` signal is already connected in several tasks
  bt/tasks/blackboard/bt_check_var.cpp
  bt/tasks/blackboard/bt_set_var.cpp
  bt/tasks/scene/bt_await_animation.cpp
  bt/tasks/scene/bt_check_agent_property.cpp
  bt/tasks/scene/bt_pause_animation.cpp
  bt/tasks/scene/bt_play_animation.cpp
  bt/tasks/scene/bt_set_agent_property.cpp
  bt/tasks/scene/bt_stop_animation.cpp
  bt/tasks/utility/bt_call_method.cpp
  bt/tasks/utility/bt_evaluate_expression.cpp
Labels: bug

#181 Implement `BTInstance` - runtime instance of `BehaviorTree`
  blackboard/bb_variable.cpp
  bt/behavior_tree.cpp
  bt/behavior_tree.h
  bt/bt_instance.cpp
  bt/bt_instance.h
  bt/bt_player.cpp
  bt/bt_player.h
  bt/bt_state.cpp
  bt/bt_state.h
  config.py
  demo/demo/scenes/showcase.gd
  demo/demo/scenes/showcase.tscn
  doc/source/classes/class_behaviortree.rst
  doc/source/classes/class_behaviortreedata.rst
  doc/source/classes/class_btinstance.rst
  doc/source/classes/class_btplayer.rst
  doc/source/classes/class_btstate.rst
  doc_classes/BTInstance.xml
  doc_classes/BTPlayer.xml
  doc_classes/BTState.xml
  doc_classes/BehaviorTree.xml
  doc_classes/BehaviorTreeData.xml
  editor/debugger/behavior_tree_data.cpp
  editor/debugger/behavior_tree_data.h
  editor/debugger/limbo_debugger.cpp
  editor/debugger/limbo_debugger.h
  editor/debugger/limbo_debugger_plugin.cpp
  editor/debugger/limbo_debugger_plugin.h
  register_types.cpp
  util/limbo_compat.h
  util/limbo_string_names.cpp
  util/limbo_string_names.h
Labels: enhancement, breaking-compatibility

#182 Allow monitoring BT performance in `BTState`
  bt/bt_state.cpp
  bt/bt_state.h
  doc/source/classes/class_btstate.rst
  doc_classes/BTState.xml
Labels: enhancement

#183 BTPlayer: Allow switching BT instance at runtime
  bt/behavior_tree.cpp
  bt/bt_instance.cpp
  bt/bt_instance.h
  bt/bt_player.cpp
  bt/bt_player.h
  doc/source/classes/class_behaviortree.rst
  doc/source/classes/class_btinstance.rst
  doc/source/classes/class_btplayer.rst
  doc_classes/BTInstance.xml
  doc_classes/BTPlayer.xml
  doc_classes/BehaviorTree.xml
Labels: enhancement

#184 Allow supplying custom scene root for behavior tree instantiation
  bt/behavior_tree.cpp
  bt/behavior_tree.h
  bt/bt_player.cpp
  bt/bt_player.h
  bt/bt_state.cpp
  bt/bt_state.h
  doc/source/classes/class_behaviortree.rst
  doc/source/classes/class_btplayer.rst
  doc/source/classes/class_btstate.rst
  doc_classes/BTPlayer.xml
  doc_classes/BTState.xml
  doc_classes/BehaviorTree.xml
Labels: enhancement

#185 Editor setting to prefer online docs, and open builtin docs by default
  editor/limbo_ai_editor_plugin.cpp
  util/limbo_compat.cpp
  util/limbo_compat.h
  util/limbo_utility.cpp
Labels: enhancement

#186 Edit task script on double-click (open help for core task)
  editor/limbo_ai_editor_plugin.cpp
  editor/limbo_ai_editor_plugin.h
Labels: enhancement

#188 Fix C# exports print errors due to missing ClassDB binding
  bt/tasks/bt_task.cpp
  bt/tasks/bt_task.h
Labels: bug

#189 Make player filter in the debugger case-insensitive
  editor/debugger/limbo_debugger_plugin.cpp
Labels: enhancement

#191 Fix renaming `BehaviorTree` files doesn't update tab names
  editor/limbo_ai_editor_plugin.cpp
  editor/limbo_ai_editor_plugin.h
Labels: bug

#193 Fix `monitor_performance` screwing C# exports
  bt/bt_player.cpp
  bt/bt_player.h
  bt/bt_state.cpp
  bt/bt_state.h
Labels: bug

#195 BlackboardPlan: Fix mapping failing for NodePath variables with prefetch enabled
  blackboard/blackboard_plan.cpp
Labels: bug

#197 GHA: Preserve nuget version for C# builds
  .github/workflows/windows.yml
Labels: github-actions

#198 Don't overwrite exisiting blackboard variables in `BTState` upon initialization
  blackboard/blackboard.h
  blackboard/blackboard_plan.cpp
  bt/bt_player.cpp
  hsm/limbo_state.cpp
Labels: bug

#199 GHA: .NET build workflow fixes
  .github/workflows/android.yml
  .github/workflows/ios.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: bug, github-actions

#200 GHA: Build additional .NET templates - Android & iOS
  .github/workflows/android.yml
  .github/workflows/ios.yml
Labels: github-actions

#201 Fix editor undo polluting scene history if `BehaviorTree` is not saved to a file
  bt/bt_instance.cpp
  bt/tasks/bt_task.cpp
  editor/limbo_ai_editor_plugin.cpp
  editor/limbo_ai_editor_plugin.h
  editor/task_palette.cpp
  hsm/limbo_hsm.cpp
  hsm/limbo_state.cpp
  util/limbo_string_names.cpp
  util/limbo_string_names.h
Labels: bug

#202 Fix custom scene root is not used in BTPlayer and BTState
  bt/bt_player.cpp
  bt/bt_state.cpp
Labels: bug
