Repository limbonaut/limboai, pull requests merged in 2024-04, with the labels that each got.

#85 `BlackboardPlan` fixes
  blackboard/blackboard_plan.cpp
  bt/behavior_tree.cpp
  bt/bt_player.cpp
  bt/bt_state.cpp
  doc/source/classes/class_behaviortree.rst
  doc_classes/BehaviorTree.xml
  hsm/limbo_state.cpp
  hsm/limbo_state.h
  util/limbo_compat.h
  util/limbo_string_names.cpp
  util/limbo_string_names.h
Labels: bug, enhancement

#87 GHA: Provide version.txt with GDExtension builds & demo project
  .github/workflows/demo.yml
  .github/workflows/gdextension.yml
Labels: github-actions

#88 GHA: Build .NET binaries for macOS
  .github/workflows/macos.yml
Labels: github-actions

#91 HSM: Delay state transition till update is finished
  bt/bt_state.cpp
  hsm/limbo_hsm.cpp
  hsm/limbo_hsm.h
Labels: bug

#92 Support multiple debugger sessions
  editor/debugger/limbo_debugger_plugin.cpp
  editor/debugger/limbo_debugger_plugin.h
  editor/limbo_ai_editor_plugin.cpp
Labels: bug, enhancement

#93 Fix `LimboState::get_root` and `dispatch` freeze the process in case of nested HSMs
  hsm/limbo_state.cpp
Labels: bug

#96 Documentation update - BTSubTree
  doc/source/classes/class_btsubtree.rst
  doc_classes/BTSubtree.xml
Labels: documentation

#89 Blackboard: Add `create` parameter to `bind_var_to_property` and `link_var`
  blackboard/blackboard.cpp
  blackboard/blackboard.h
  doc/source/classes/class_blackboard.rst
  doc_classes/Blackboard.xml
Labels: enhancement

#95 BTDecorator: Add default `_tick` implementation
  bt/tasks/bt_decorator.cpp
  bt/tasks/bt_decorator.h
Labels: enhancement
