Repository limbonaut/limboai, pull requests merged in 2025-02, with the labels that each got.

#280 Doc: Mention pre-built templates
  doc/source/getting-started/getting-limboai.rst
Labels: documentation

#279 Fix duplicate UI banners
  editor/limbo_ai_editor_plugin.cpp
Labels: bug

#284 GDExtension: Build Android libs with editor features
  .github/workflows/gdextension.yml
  .github/workflows/macos.yml
  gdextension/limboai.gdextension
Labels: bug

#285 GHA: Build editor targets for iOS & Web GDExtension libs
  .github/workflows/gdextension.yml
  gdextension/limboai.gdextension
Labels: github-actions

#223 Support Godot 4.4
  blackboard/bb_param/bb_node.cpp
  blackboard/blackboard_plan.cpp
  bt/behavior_tree.cpp
  bt/bt_instance.cpp
  bt/bt_state.cpp
  bt/tasks/bt_comment.cpp
  bt/tasks/bt_task.cpp
  bt/tasks/decorators/bt_cooldown.cpp
  bt/tasks/decorators/bt_new_scope.cpp
  editor/blackboard_plan_editor.cpp
  editor/debugger/limbo_debugger_plugin.cpp
  editor/editor_property_bb_param.cpp
  editor/editor_property_property_path.cpp
  editor/editor_property_variable_name.cpp
  editor/limbo_ai_editor_plugin.cpp
  editor/limbo_ai_editor_plugin.h
  editor/mode_switch_button.h
  editor/task_palette.cpp
  editor/task_tree.cpp
  editor/tree_search.cpp
  tests/test_task.h
  util/limbo_compat.cpp
  util/limbo_compat.h
  util/limbo_utility.cpp
Labels: enhancement

#287 BBParam editor property for GDExtension
  compat/forward_decl.h
  editor/editor_property_bb_param.cpp
  editor/editor_property_bb_param.h
  editor/limbo_ai_editor_plugin.cpp
  register_types.cpp
  util/limbo_string_names.cpp
  util/limbo_string_names.h
Labels: enhancement

#290 Toggle unhandled_input processing in HSM
  hsm/limbo_hsm.cpp
  hsm/limbo_state.cpp
Labels: enhancement

#300 Feature: Make editor actions work with multi-selection
  editor/limbo_ai_editor_plugin.cpp
  editor/limbo_ai_editor_plugin.h
  editor/task_tree.cpp
Labels: enhancement
